# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewSaltstackMinionsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP')),
                ('hostname', models.CharField(max_length=128, verbose_name='主机名')),
                ('zombie_process', models.IntegerField(verbose_name='僵死进程数量')),
                ('mem_use_precent', models.FloatField(max_length=4, verbose_name='内存使用率')),
                ('up_time', models.CharField(max_length=128, verbose_name='系统运行时间')),
                ('load_average_fiveMin_ago', models.FloatField(verbose_name='系统五分钟以内的负载')),
                ('cpu_ioWait', models.FloatField(verbose_name='CPU IoWait')),
                ('login_users', models.CharField(max_length=128, verbose_name='登陆用户数量')),
                ('disk_max_usage', models.FloatField(verbose_name='磁盘最大使用率')),
                ('update_time', models.DateTimeField(verbose_name='数据更新时间')),
                ('poweron_time', models.DateTimeField(verbose_name='系统开机时间')),
            ],
            options={
                'verbose_name_plural': '系统状态',
                'verbose_name': '系统状态',
            },
        ),
        migrations.CreateModel(
            name='SaltstackGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, verbose_name='组名')),
                ('whether_create', models.IntegerField(default=0, verbose_name='是否创建了组在saltstack配置文件里')),
                ('tags', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='SaltstackMinions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('hostname', models.CharField(max_length=255, verbose_name='Minion的主机名')),
                ('tags', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='SaltstackMinionsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP')),
                ('hostname', models.CharField(max_length=128, verbose_name='主机名')),
                ('zombie_process', models.IntegerField(verbose_name='僵死进程数量')),
                ('mem_use_precent', models.FloatField(max_length=4, verbose_name='内存使用率')),
                ('up_time', models.CharField(max_length=128, verbose_name='系统运行时间')),
                ('load_average_fiveMin_ago', models.FloatField(verbose_name='系统五分钟以内的负载')),
                ('cpu_ioWait', models.FloatField(verbose_name='CPU IoWait')),
                ('login_users', models.CharField(max_length=128, verbose_name='登陆用户数量')),
                ('disk_max_usage', models.FloatField(verbose_name='磁盘最大使用率')),
                ('update_time', models.DateTimeField(verbose_name='数据更新时间')),
                ('poweron_time', models.DateTimeField(verbose_name='系统开机时间')),
            ],
            options={
                'verbose_name_plural': '系统5分钟内运行状态',
                'verbose_name': '系统5分钟内运行状态',
            },
        ),
        migrations.AddField(
            model_name='saltstackgroup',
            name='group_number',
            field=models.ManyToManyField(blank=True, null=True, to='Batch.SaltstackMinions', verbose_name='组成员'),
        ),
    ]
