# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0002_auto_20161223_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproject',
            name='name_of_project',
            field=models.CharField(max_length=255, verbose_name='项目名字'),
        ),
    ]
