# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0003_auto_20161223_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saltstackgroup',
            options={'verbose_name': 'saltstack组信息', 'verbose_name_plural': 'saltstack组信息'},
        ),
        migrations.AlterModelOptions(
            name='saltstackminions',
            options={'verbose_name': 'saltstack minion信息', 'verbose_name_plural': 'saltstack minion信息'},
        ),
        migrations.AlterModelOptions(
            name='typeofapp',
            options={'verbose_name': '应用类型', 'verbose_name_plural': '应用类型'},
        ),
        migrations.AlterModelOptions(
            name='typeofproject',
            options={'verbose_name': '项目列表', 'verbose_name_plural': '项目列表'},
        ),
        migrations.AlterModelOptions(
            name='workorderofcodeupdate',
            options={'verbose_name': '代码更新工单记录', 'verbose_name_plural': '代码更新工单记录'},
        ),
        migrations.AlterModelOptions(
            name='workorderofconfigfile',
            options={'verbose_name': '配置文件更改工单记录', 'verbose_name_plural': '配置文件更改工单记录'},
        ),
        migrations.AlterModelOptions(
            name='workorderofdatabasechange',
            options={'verbose_name': '数据库更新工单操作记录', 'verbose_name_plural': '数据库更新工单操作记录'},
        ),
        migrations.AlterModelOptions(
            name='workorderoftype',
            options={'verbose_name': '工单类型', 'verbose_name_plural': '工单类型'},
        ),
        migrations.RemoveField(
            model_name='workorderofcodeupdate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workorderofconfigfile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workorderofdatabasechange',
            name='id',
        ),
        migrations.AddField(
            model_name='workorderofcodeupdate',
            name='OrderId',
            field=models.CharField(default='201612250124', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
        migrations.AddField(
            model_name='workorderofconfigfile',
            name='OrderId',
            field=models.CharField(default='201612250124', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
        migrations.AddField(
            model_name='workorderofdatabasechange',
            name='OrderId',
            field=models.CharField(default='201612250124', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
        migrations.AlterField(
            model_name='workorderofcodeupdate',
            name='flow_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Batch.TypeOfApp', verbose_name='归属应用'),
        ),
        migrations.AlterField(
            model_name='workorderofcodeupdate',
            name='flow_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Batch.TypeOfProject', verbose_name='归属项目'),
        ),
        migrations.AlterField(
            model_name='workorderofcodeupdate',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Batch.WorkOrderOfType', verbose_name='工单操作类型'),
        ),
        migrations.AlterField(
            model_name='workorderofdatabasechange',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Batch.WorkOrderOfType', verbose_name='工单操作类型'),
        ),
    ]
