# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0004_auto_20161223_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderofconfigfile',
            name='flow_app',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Batch.TypeOfApp', verbose_name='归属应用'),
        ),
    ]
