# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0005_workorderofconfigfile_flow_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderofcodeupdate',
            name='OrderId',
            field=models.CharField(default='20161223173550', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
        migrations.AlterField(
            model_name='workorderofconfigfile',
            name='OrderId',
            field=models.CharField(default='20161223173550', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
        migrations.AlterField(
            model_name='workorderofdatabasechange',
            name='OrderId',
            field=models.CharField(default='20161223173550', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
