# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0006_auto_20161223_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderofcodeupdate',
            name='OrderId',
            field=models.CharField(default='20161224162437', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
        migrations.AlterField(
            model_name='workorderofcodeupdate',
            name='email_issend',
            field=models.BooleanField(verbose_name='提醒邮件是否已经发送'),
        ),
        migrations.AlterField(
            model_name='workorderofcodeupdate',
            name='system_env_change',
            field=models.CharField(blank=True, max_length=10240, null=True, verbose_name='系统环境变更'),
        ),
        migrations.AlterField(
            model_name='workorderofcodeupdate',
            name='update_of_reason',
            field=models.CharField(blank=True, max_length=10240, null=True, verbose_name='更新原因'),
        ),
        migrations.AlterField(
            model_name='workorderofconfigfile',
            name='OrderId',
            field=models.CharField(default='20161224162437', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
        migrations.AlterField(
            model_name='workorderofdatabasechange',
            name='OrderId',
            field=models.CharField(default='20161224162437', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
