# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0008_auto_20161224_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorderofupdate',
            options={'verbose_name': '更新工单记录', 'verbose_name_plural': '更新工单记录'},
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20161224163421', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='code_source',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='源码来源'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='configfile_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='配置文件路径'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='whether_update_code',
            field=models.BooleanField(default=False, verbose_name='是否更新代码'),
        ),
    ]
