# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0009_auto_20161224_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofproject',
            name='include_apps',
        ),
        migrations.AddField(
            model_name='typeofproject',
            name='include_apps',
            field=models.ManyToManyField(to='Batch.TypeOfApp'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20161225093846', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
