# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-25 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0010_auto_20161225_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderofupdate',
            name='whether_change_configfile',
        ),
        migrations.RemoveField(
            model_name='workorderofupdate',
            name='whether_change_crond',
        ),
        migrations.RemoveField(
            model_name='workorderofupdate',
            name='whether_change_database',
        ),
        migrations.RemoveField(
            model_name='workorderofupdate',
            name='whether_update_code',
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20161225171816', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
