# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0014_auto_20161225_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorderofupdate',
            old_name='edit_configfile',
            new_name='configfile_content',
        ),
        migrations.RemoveField(
            model_name='workorderofupdate',
            name='order_type',
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20161225214347', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
        migrations.DeleteModel(
            name='WorkOrderOfType',
        ),
    ]
