# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0016_auto_20161226_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderofupdate',
            name='accessory_path',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20161227152658', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
