# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0018_auto_20161227_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20161228141519', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='accessory_path',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='附件路径'),
        ),
    ]
