# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0019_auto_20161228_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerContainers',
            fields=[
                ('Container_id', models.CharField(max_length=400, primary_key=True, serialize=False, verbose_name='容器ID')),
                ('Container_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='容器名字')),
                ('Container_image', models.CharField(max_length=300, verbose_name='容器镜像')),
                ('Container_Image_id', models.CharField(max_length=500, verbose_name='镜像ID')),
                ('Command', models.CharField(blank=True, max_length=300, null=True, verbose_name='运行的命令')),
                ('Created', models.DateField(verbose_name='创建时间')),
                ('Status', models.CharField(max_length=100, verbose_name='运行状态')),
                ('Port', models.CharField(blank=True, max_length=1000, null=True, verbose_name='容器端口')),
                ('SizeRw', models.IntegerField()),
                ('SizeRootFs', models.IntegerField()),
                ('Host_config', models.CharField(max_length=1024, verbose_name='主机配置')),
                ('Network_settings', models.CharField(max_length=3000, verbose_name='网络配置')),
                ('Mounts', models.CharField(max_length=1024, verbose_name='挂载目录')),
            ],
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20161228154811', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
