# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0021_auto_20161228_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockercontainers',
            name='Real_host_ip',
            field=models.GenericIPAddressField(default=None, verbose_name='容器宿主机IP'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20161228164604', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
