# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0022_auto_20161228_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockercontainers',
            name='Real_host_ip',
            field=models.CharField(default=None, max_length=128, verbose_name='容器宿主机IP'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20161229104557', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
