# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0023_auto_20161229_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockercontainers',
            name='Container_Image_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='镜像ID'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20161229104730', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
