# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0024_auto_20161229_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerOfHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.CharField(max_length=250, verbose_name='Docker宿主机IP')),
            ],
            options={
                'verbose_name': 'Docker宿主机IP',
                'verbose_name_plural': 'Docker宿主机IP',
            },
        ),
        migrations.AlterField(
            model_name='dockercontainers',
            name='Record_time',
            field=models.DateField(verbose_name='数据更新时间'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20161231223905', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
