# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0026_auto_20161231_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20170101004200', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
