# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0028_auto_20170101_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerofhost',
            name='host_ip',
            field=models.CharField(max_length=250, unique=True, verbose_name='Docker宿主机IP'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20170101014941', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
