# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0031_auto_20170101_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockercontainers',
            name='Real_host_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Batch.DockerOfHost', verbose_name='Docker宿主机IP'),
        ),
        migrations.AlterField(
            model_name='dockercontainers',
            name='Record_time',
            field=models.DateTimeField(auto_now=True, verbose_name='数据更新时间'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20170101021852', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
