# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0032_auto_20170101_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerOfImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_id', models.CharField(max_length=300, verbose_name='镜像ID')),
                ('Parent_id', models.CharField(default=None, max_length=300, verbose_name='父级镜像ID')),
                ('Repo_tags', models.CharField(default=None, max_length=300, verbose_name='仓库备注')),
                ('Repo_digests', models.CharField(default=None, max_length=300, verbose_name='')),
                ('Created', models.CharField(default=None, max_length=200, verbose_name='创建时间')),
                ('Image_size', models.CharField(default=None, max_length=300, verbose_name='镜像实际大小')),
                ('Virtual_size', models.CharField(max_length=300, verbose_name='镜像虚拟大小')),
                ('Labels', models.CharField(default=None, max_length=300, verbose_name='标签')),
                ('Host_ip', models.ManyToManyField(to='Batch.DockerOfHost', verbose_name='Docker宿主机IP')),
            ],
            options={
                'verbose_name_plural': 'Docker镜像',
                'verbose_name': 'Docker镜像',
            },
        ),
        migrations.AlterField(
            model_name='dockercontainers',
            name='Container_id',
            field=models.CharField(max_length=400, primary_key=True, serialize=False, unique=True, verbose_name='容器ID'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20170104163842', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
