# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0033_auto_20170104_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerofimages',
            name='Repo_digests',
            field=models.CharField(default=None, max_length=300, verbose_name='仓库摘要'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20170105114539', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
