# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0034_auto_20170105_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20170105144253', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
