# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0035_auto_20170105_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerofimages',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20170106182344', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
