# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0037_auto_20170210_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsaltstackminionsstatus',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Batch.Asset', verbose_name='资产编号'),
        ),
        migrations.AddField(
            model_name='saltstackminionsstatus',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Batch.Asset', verbose_name='资产编号'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20170217163713', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
