# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0041_auto_20170220_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20170220142913', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
