# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0044_auto_20170220_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvehosts',
            name='asset_id',
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20170220154543', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
