# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0046_auto_20170221_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='disk_size_in_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='磁盘总量'),
        ),
        migrations.AddField(
            model_name='ram',
            name='ram_size_in_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='内存总量'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20170223170346', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
