# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0048_auto_20170223_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nic',
            name='macaddress',
            field=models.CharField(max_length=64, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='workorderofupdate',
            name='OrderId',
            field=models.CharField(default='20170223181123', max_length=128, primary_key=True, serialize=False, verbose_name='工单ID'),
        ),
    ]
